all-features = true

[advisories]
notice = "deny"
unmaintained = "deny"
unsound = "deny"
vulnerability = "deny"
yanked = "deny"

[licenses]
allow-osi-fsf-free = "both"
confidence-threshold = 1
copyleft = "allow"
default = "deny"
unlicensed = "deny"
allow = [
    "Unicode-DFS-2016"
]

[sources]
unknown-registry = "deny"